<?php
require_once('traits/Basededatos.php');
require_once('interfaz/IEnviarDatos.php');
require_once('interfaz/IConsultarDatos.php');
require_once('interfaz/IEjecutarSQL.php');
require_once('classes/LibrosBD.php');
require_once('Libros/Copias.php');
require_once('classes/AutoresBD.php');
require_once('classes/TiposDeLibrosBD.php');